# fly.toml app configuration for ols-viikkopelit-admin (ADMIN APP - PRIMARY/WRITER)
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'ols-viikkopelit-admin'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

# ADMIN APP NEEDS A VOLUME - It's the primary database
[[mounts]]
  source = 'ols_admin_data'
  destination = '/var/lib/litefs'  # LiteFS data directory

[http_service]
  internal_port = 8080      # LiteFS proxy port
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "3s"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
