# fly.toml app configuration file generated for ols-viikkopelit-admin on 2025-05-28T12:28:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ols-viikkopelit-admin'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'ols_admin_data'
  destination = '/data'

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "3s"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
